Use unpacked Runtime APEX in ART chroot-based device testing.
Push the unpacked Debug Runtime Module
directory (`$ANDROID_PRODUCT_OUT/apex/com.android.runtime.debug`),
built along with the Debug Runtime APEX package
(`$ANDROID_PRODUCT_OUT/system/apex/com.android.runtime.debug.apex`).
to directory `/apex/com.android.runtime` under the chroot directory on
the device. This directory contains the same files as the Runtime APEX
and is a sufficiently good approximation of a mounted Runtime Module
to be used for ART testing.

Also avoid generating artifacts that are not expected in the `system`
directory (`TARGET_OUT`) of a "normal" build. Instead, rely on scripts
`tools/setup-buildbot-device.sh` and `tools/buildbot-sync.sh` to
provide the missing files directly under the chroot directory on the
device.

Honor a `ART_TEST_LD_CONFIG_FILE` environment in all ART test scripts,
which is expected to be set to a specific linker configuration file
when running a "guest" minimal system (in the chroot environment)
built with a specific linker configuration, independent from the one
of the "host" device (see
https://android-review.googlesource.com/c/device/generic/art/+/921734).

Test: ART chroot-based on-device testing using the master branch
Test: ART chroot-based on-device testing using the master-art branch
Bug: 124425036
Bug: 121117762
Change-Id: Ied3f6ee8b2d68c3473fab864d1bbed9e88df59d3

diff --git a/test/run-test b/test/run-test
--- a/test/run-test
+++ b/test/run-test
@@ -407,6 +407,15 @@ while true; do
         fi
         run_args="${run_args} --android-runtime-root $1"
         shift
+    elif [ "x$1" = "x--ld-config-file" ]; then
+        shift
+        if [ "x$1" = "x" ]; then
+            echo "$0 missing argument to --ld-config-file" 1>&2
+            usage="yes"
+            break
+        fi
+        run_args="${run_args} --ld-config-file $1"
+        shift
     elif [ "x$1" = "x--update" ]; then
         update_mode="yes"
         shift
@@ -787,6 +796,11 @@ if [ "$usage" = "yes" ]; then
         echo "    --android-runtime-root [path]"
         echo "                          The path on target for the Android Runtime root."
         echo "                          (/apex/com.android.runtime by default)."
+        echo "    --ld-config-file [path]"
+        echo "                          The path on target to the linker configuration file"
+        echo "                          (not defined by default). Note: The linker will ignore"
+        echo "                          this option when executed on a device running a 'user'"
+        echo "                          build."
         echo "    --dex2oat-swap        Use a dex2oat swap file."
         echo "    --instruction-set-features [string]"
         echo "                          Set instruction-set-features for compilation."
